version: '3.3'

services:
  main_db:
    image: postgres:alpine
    container_name: main_postgres
    command: postgres -c 'max_connections=50'
    environment:
      TZ: 'Europe/Lisbon'
    ports:
      - 5432
    restart: unless-stopped
    volumes:
      - ./database/dumps/init_server.sql:/docker-entrypoint-initdb.d/init_server.sql
    env_file:
      - ./database/main_database.dev.env
    networks:
      main_network:
        ipv4_address: 172.40.0.10
  server:
    build: ./main-server/web-server
    image: netmonit-server
    container_name: server
    environment:
      TZ: 'Europe/Lisbon'
    hostname: localhost
    depends_on:
      - main_db
    ports: 
      - 8080
    restart: unless-stopped
    network_mode: host
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - main_db
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafanareader
      - GF_INSTALL_PLUGINS=
    networks:
      main_network:
        ipv4_address: 172.40.0.11
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
  
volumes:
  grafana_data: {}

networks:
  main_network:
    ipam:
      config:
        - subnet: 172.40.0.0/16
