version: '3.3'

services:
  main_db:
    image: postgres:alpine
    container_name: main_postgres
    command: postgres -c 'max_connections=50'
    ports:
      - 5432
    restart: unless-stopped
    volumes:
      - ./database/dumps/init_server.sql:/docker-entrypoint-initdb.d/init_server.sql
    env_file:
      - ./database/main_database.dev.env
    networks:
      main_network:
        ipv4_address: 172.40.0.10
  server:
    build: ./main-server/web-server
    image: netmonit-server
    container_name: server
    hostname: localhost
    depends_on:
      - main_db
    ports: 
      - 8080
    restart: unless-stopped
    network_mode: host

networks:
  main_network:
    ipam:
      config:
        - subnet: 172.40.0.0/16
